spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: guru #typically password is loaded from ENVIRONMENT variable
  jpa:
    hibernate:
      ddl-auto: validate #it checks ( validates ) if schema is as we expect - create-drop is default by Spring Boot
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true